### ISSUE TITLE
optimizer bug: inserts constant instead of variable

### ISSUE THREAD

**Issue by meisl** [irmen/prog8#31] opened 2021-05-04 13:34 UTC
Hi,

there seems to be a bug in the optimizer when it comes to [constant folding/propagation](https://en.wikipedia.org/wiki/Constant_folding#Constant_propagation) (wrt. strings/characters in this case).

* prog8 version: 6.4
* command: `java -jar ../prog8compiler-6.4-all.jar -target cx16 p8-bug_str-opt.p8`
* source code:
```
%target cx16
%import textio
%zeropage basicsafe
%option no_sysinit

main {
	str   input = "1234"
	ubyte index = 0
	str   temp  = "?"

	sub start() {
		ubyte @zp ch
		
		repeat {
			ch = input[index]
			when ch {
				0 -> {
					break
				}
				else -> {
                                        temp[0] = ch ; <<<<<<<<<<<<<
					txt.print(temp) ; wrongly optimized to
					;      lda #$3f
					;      jsr txt.chrout

					; with -noopt it's correctly turned into
					;      ldy  #>temp
					;      ldy  #<temp
					;      jsr  txt.print
				}
			}
			index++
		}
		return
	}
}
```
* expected assembly (properly optimized away the access to temp, see remarks below):
```
    	;	src line: p8-bug_str-opt.p8:21
	lda  ch
	sta  temp+0
	;	src line: p8-bug_str-opt.p8:22
	jsr  txt.chrout
```
* actual assembly:
```
	;	src line: p8-bug_str-opt.p8:21
	lda  ch
	sta  temp+0
	;	src line: p8-bug_str-opt.p8:22
	lda  #$3f
	jsr  txt.chrout
```
* Remarks:
  - With `-noopt` of course correct code is generated
  - What I'd "expected" as an optimization - if at all - is the elimination of the access to temp; constant folding/propagation however is not applicable here. But note: this depends on the string `temp` to be only one character long (so we could use `txt.chrout` rather than `txt.print`. This is by no means a simple "peephole" optimization, so better not try such "stunts" at all - at least at this stage.
  - I could provide the two `.asm` files for convenience if desired, but rather not here in the OP, as they are of course rather long.

**Comment by irmen** [comment] 2021-05-04 21:03
It's not wrong, and not a "stunt". This is by design. Prog8 currently optimizes as follows:
-  a string print of strings of a single character is turned into a single CHROUT call.
-  as strings are assumed to be static, the compiler can perform the above optimization, and also does string interning and overlapping of identical constants.

The documentation warns you about this : https://prog8.readthedocs.io/en/latest/programming.html#strings  (see the caution block)
It doesn't mention the above consequences there though, which is an oversight. 

Now, the question is if the current behavior is _desirable_.  It hasn't been a problem so far, but does lead to some unexpected results as your example shows.  I'll give it some thought.

**Comment by meisl** [comment] 2021-05-04 22:18
Ooh... I totally missed that in the docs. Sorry.

As to whether it's desirable: well, I'm not entirely sure either.
However, *if* string *contents* are to be immutable (not the string *vars*, as they are pointers), *then* such an assignment `strvar[idx] = 'x'` should be an error or a warning, I think. I don't know about your type system, but that shouldn't be too hard. I mean simply don't allow indexing into a string on the lhs.
On the other hand, something like `@(&strvar + idx) = 'x'` is probably harder to spot, so in that case I'd rather say "well, you seem to be asking for trouble, so..."

In any case, there's still something weird going on: I just changed the `temp` string to two characters, ie `str temp = "??"` and compiled it with optimization on. It *still* generates
```
        ;	src line: p8-bug_str-opt.p8:21
	lda  ch
	sta  temp+0
	;	src line: p8-bug_str-opt.p8:22
	lda  #$3f
	jsr  txt.chrout
```
So it prints only one `?`, not two. That's definitely wrong.

**Comment by meisl** [comment] 2021-05-04 22:21
Oh, oh, sorry again! **It's correct, it does it twice:**
```
	;	src line: p8-bug_str-opt.p8:22
	lda  #$3f
	jsr  txt.chrout
	;	src line: p8-bug_str-opt.p8:23
	lda  #$3f
	jsr  txt.chrout
```

**Comment by irmen** [comment] 2021-05-04 22:30
Well, the string type is actualy a weird thing in prog8 right now.
It's NOT a pointer type, although it behaves like one in certain situations (for example you can take the address of it explicitly, yielding the actual pointer to the start of the string, or it is autoconverted to that address if its assigned to an uword parameter etc.)  But the str-variable itself is not represented in memory other than just the interned string literal.
So this might explain to you some of your observations.

It could be made immutabile and don't allow modification in the LHS but that's hard to enforce especially because you can destroy everything with just a few simple assembly instructions in an embedded asm block that modify the string, this can't be detected.

We could decide to drop the immutabily aspect and remove some optimizations but I really want to keep the string literal interning that gets rid of duplicates...  (then again, how often do these occur?)

It's also clear now that the documentation needs some work :)

**Comment by meisl** [comment] 2021-05-04 23:20
Hm, tough question(s) indeed. Depends on where you want to go with prog8, I mean you, as the designer.

I, personally, started looking into it because it kinda makes assembler viable, so to speak, but still allows low level tweaking. NOT because of optimizations. One thing's for sure: this nature of strings as it is now is not what one would expect.

> because you can destroy everything with just a few simple assembly instructions in an embedded asm block that modify the string, this can't be detected.

Sure, then all bets are off. That's what I meant with `@(&strvar + idx) = ...`. But then it's pretty clear to the programmer, that they're on their own. Doesn't keep you from disallowing `strvar[index]` on the LHS.

I have to think about this more. But for now, here's what came to my mind right now (read as maybes):
* rather than "all or nothing", provide command line switches for certain optimizations, eg `-Ostrings` or similar
* default to no optimizations at all or only some definitely indisputable ones (e.g. not including stuff that's not used, if that's even an "optimization")
* extra type for those not-mess-with strings? But how to call them?

**Comment by meisl** [comment] 2021-05-05 17:31
Hi @irmen,
I think we've got three things so far:
* Technically, this issue can be closed since it's not a bug as such, like you explained.
* *Something* has to be done w.r.t. strings, be it just to improve the docs or maybe rework and/or a new approach.
* For the latter a dedicated discussion might be good to have first, to sort things out: new issue, with ref to this one, and OP containing the questions, as far as we can see now.

I think I know pretty well how you feel about your work re interned strings. But strings are also notoriously difficult to get right (ie: to get their *design* right in a language). Doesn't necessarily mean you have to ditch all your work though.

Anyways, if you do want a discussion, I'll be there; just tell me. If you don't, well then that's ok, too; no hard feelings. It's your language, after all.

**Comment by irmen** [comment] 2021-05-05 18:01
I'm leaning towards dropping the immutability aspect of strings (and thus the deduplication/interning). Maybe that can still be done with a command line switch as you pointed out.

In the meantime you can avoid the issue I think by making your string 2 characters long instead of just 1

**Comment by meisl** [comment] 2021-05-12 16:12
Hi @irmen,

I've seen you [removed the one/two character string optimization](8736da1a2119627a22f06a1a4a17348e40715a2d) already. I won't complain too much about that, but as said, could still be applied to provably constant strings (such as string literals appearing as parameter).

Anyways, the general question re strings is of course larger, and a tough one. I'm thinking about something in the form of #38. What do you think?

One more thing: labels. There are a few (now closed) issues which should get the "bug" label: #29, #34, #37. Finally, I'd suggest you create a new label "not a bug", and attach it to this one.

**Comment by irmen** [comment] 2021-05-12 22:08
I don't use labeling much to be honest...  also often 'enhancement' or 'question' is good enough for me too !

Yeah I'm playing around a bit with issues mentioned in this topic. The thought did already cross my mind to make special exceptions for literals used as arguments because they indeed can be "expected to be constant"...

**Comment by meisl** [comment] 2021-05-12 23:33
So what started out as a presumed bug (presumed by me), now not only is *not* a bug but has even become an "enhancement"... :D

But seriously, labels aren't so important as long as there aren't too many issues. That is, a few tens or so, as there are right now. But it doesn't take much more - issues and/or people - and they (the labels) do help a lot. And it's practically zero effort to put them on. Btw: there shouldn't be too many different labels either, but "not-a-bug" is a useful and common one.

> Yeah I'm playing around a bit with issues mentioned in this topic.

Yep, pleased to see your interest. I still think a new, dedicated issue with "Rationale", "Proposal" etc. would be appropriate, but we can as well continue here, if you prefer.

> for literals used as arguments because they indeed can be "expected to be constant"...

That's exactly the point: any optimization must be *provably* correct, ie. yield the same computational semantics as without it. Otherwise it is not an optimization, just unspecified, practically unpredictable, weird/aberrant edge-case behaviour. At least that's the impression on the user (programmer).

Strings that cannot be referred to other than stating them literally *are* constant. That's true for those that are passed literally as arguments. But maybe one could also have some strings named, but explicitly marked as immutable. Note that `const`, to be precise, has a slightly different meaning: it fixes the *binding* of the name to the representation, but not the representation itself. That's part of our problem here.
I'm of course speaking only in terms of the Prog8 language. If the user chooses to "go `asm`" - or even only "strip off the type" by `@(&strvar)` - then they're on their own. *But at least they had to be explicit about it then.*

**Comment by irmen** [comment] 2021-05-19 14:26
have been changing the docs about strings a bit to hopefully make it more clear ca1a8cd617bbdf2b201120720d4c83ded43aeb80 
deduplication now only is done on constant string literals
Combined with the earlier changes in the optimizer, I think we kinda have arrived at a workable solution now?

**Comment by meisl** [comment] 2021-05-19 17:33
Yep, looking good to me. That way you're on the safe side, which is definitely more important.

So now there are other things to do, but I'll make extra issues for these. I'll try to make each comprehensive, so need to think about it. But to give some hints (not necessarily in order of importance): type bool, the evaluation stack, recursion, usage of zeropage vars/faulty codegen when running out of zp space.

**Comment by irmen** [comment] 2021-05-20 00:38
Okidoki I'll close this issue then.

**Closed by irmen** 2021-05-20 00:38 UTC
Labels: enhancement
