### ISSUE TITLE
Bug: file name missing in err msgs for imported files

### ISSUE THREAD

**Issue by meisl** [irmen/prog8#46] opened 2021-06-15 20:17 UTC
* **Prog8 version**: 7.0 beta2, *NOT* 6.4, goes away with PR #45 (but not properly fixed there; **see discussion below**)
* **Command line**: java -jar prog8compiler-7.0-BETA2-all.jar issue46_main.p8
* **Source code**:
  1. `issue46_main.p8`:
      ```
        %import issue46_imported
        main {
	        sub start() {
	        }
        }

      ```
  2. `issue46_imported.p8`:
      ```
        foo {
            str str ; parse error (non-lexical) -> BUG
            str bar = "missing closing quotes (lexical error) -> NO bug
        } ; incidentally, the previous lexical error yields another non-lexical one -> BUG

      ```
* **Expected**:
All error messages should state the proper file name, as in v6.4:
```
Prog8 compiler v6.4 by Irmen de Jong (irmen@razorvine.net)
This software is licensed under the GNU GPL 3.0, see https://www.gnu.org/licenses/gpl.html

Compiler target: c64. Parsing...
importing 'issue46_main'
importing 'issue46_imported' (from '.\issue46_imported.p8')
.\issue46_imported.p8:3:11: token recognition error at: '"missing closing quotes (lexical error) -> no bug\r'
.\issue46_imported.p8:2:5: no viable alternative at input 'strstr'
.\issue46_imported.p8:3:61: mismatched input '\n' expecting {'[', '+', '-', '~', 'not', '(', 'true', 'false', NAME, DEC_INTEGER, HEX_INTEGER, BIN_INTEGER, '&', '@', FLOAT_NUMBER, STRING, SINGLECHAR}
There are 3 errors in 'issue46_imported'.
```
* **Actual**:
Two of the three error messages state "\<unknown\>" instead of the file name:
```
Prog8 compiler v7.0-BETA2 by Irmen de Jong (irmen@razorvine.net)
This software is licensed under the GNU GPL 3.0, see https://www.gnu.org/licenses/gpl.html

Compiler target: c64. Parsing...
importing 'issue46_main'
importing 'issue46_imported' (from '.\issue46_imported.p8')
.\issue46_imported.p8:3:11: token recognition error at: '"missing closing quotes (lexical error) -> no bug\n'
<unknown>:2:5: no viable alternative at input 'strstr'
<unknown>:4:0: mismatched input '}' expecting {'[', '+', '-', '~', 'not', '(', 'true', 'false', NAME, DEC_INTEGER, HEX_INTEGER, BIN_INTEGER, '&', '@', FLOAT_NUMBER, STRING, SINGLECHAR}
There are 3 errors in 'issue46_imported'.
```
* **Discussion**
  - While working on #45 I was able to determine the exact reason for this, and incidentally this PR makes it go away.
  - However, a *proper* fix requires more changes, and - more importantly - *tests*. I'd volunteer for that, but would need your help, @irmen.
  - **So, what's going on?**
    * First, let's note that one of the error messages still contains the proper file name. The difference is this: lexical error (coming from the lexer -> no bug) versus non-lexical (coming from the parser -> bug).
    * The bug was introduced in b4700af2f55e118d23ad359433fbe5631289be5f, not exactly for but related to #40
    * The crucial change there (in `compilerAst/src/prog8/parser/Moduleparsing.kt`) wrt to the bug is the first argument to `importModule`; before: `CharStreams.fromPath(filePath)` (effectively) and after: `CharStreams.fromString(content)`. `content` is read from `filePath` and modified. The problem is that `CharStreams` (from antlr) remembers the file name info when called with `.fromPath`, but cannot do so when called with `.fromString`.
    * Even though the `filePath` info was still passed to `importModule` as additional argument, this then goes on and registers a custom `ErrorListener`, which in turn relies on `recognizer.inputStream.sourceName` for reporting errors - but only so for non-lexical errors. For lexical errors it uses `recognizer.modulePath`, which continued to work.
    * #45 again uses `CharStreams.fromPath(filePath)`, but obviously that's only removing the symptom, not the real cause.
   - IMHO, this is an urgent call for tests now, not least in order to prevent a regression.
   - I tried, but unfortunately I was unable to create some. Reasons: a) test *fixtures* (files) are needed (new thing in this project), plus b) getting the code under test to execute - and at best *only* that - isn't possible due to visibility issues and rather long dependency chains. I'm not brave enough for the necessary refactorings, and there are no other tests to guard me.
   - **But: I would really like to work on fixing this (incl. writing tests). I'd just need help/advice.**
* **Further notes**
  - Interesting: the errors are not reported in order, 3:11 comes before 2:5...
  - Note the 2nd msg, @ 2:5 (first in source): "...at input 'strstr'" - white space in src citation is missing
  - The main file, `issue46_main.p8` is reported as being "imported" - minor but awkward

**Comment by meisl** [comment] 2021-06-15 20:40
Proposed tests:
`testLexicalErrorLocationInMainFile`
`testNonLexicalErrorLocationInMainFile`
`testLexicalErrorLocationInImportedFile`
`testNonLexicalErrorLocationInImportedFile`

**Comment by irmen** [comment] 2021-06-18 18:45
> The main file, issue64_main.p8 is reported as being "imported" 

I think I had it printed as "loading" or "parsing" first but didn't like those terms much. I don't consider this worth any time, also you could think of the compilation process starting off by simply importing the root module of the tree of module files.

>  the errors are not reported in order, 3:11 comes before 2:5...

Probably has to do with the way the Antlr parser traverses the tree built from the tokens? Not sure. I don't find it worth improving right now as the number of errors out of order is very limited

> "...at input 'strstr'" - white space in src citation is missing

Yeah I've seen that before, not sure why antlr does this. I guess it's simply omitting all whitespace tokens also from the error message source text... I accepted it as a quirk for now.

Finally, about the problems creating tests for this: I recognize that is is hard/impossible right now  because of the dependency chains in the import mechanism.  I'll think about improving this but don't want to make big changes to it for the 7.0 release - improving testability of the code base should come later or at most be done in a separate branch for now.   
Having more unit tests is a nice thing, and will become more important once the compiler matures, but I don't see them as an urgent  necessity for the 7.0 release tbh.

**Comment by meisl** [comment] 2021-06-18 20:45
> By merging #45 the immediate problem of the missing file names has disappeared indeed.
> > The main file, issue64_main.p8 is reported as being "imported"

> I think I had it printed as "loading" or "parsing" first but didn't like those terms much. I don't consider this worth any time, also > you could think of the compilation process starting off by simply importing the root module of the tree of module files.
* it's `issue46_main.p8`, my fault; corrected in OP
* "simply importing the root module" is actually a problem, in my view. It is the root (no pun intended) of not-so-good dependencies. It made it really hard for me to wrap my head around what a `Program` (AST-node, not parse tree node) actually represents (plus: *when*). Actually, I don't think that *importing* should be done in compilerAst at all. That is already interpreting an existing AST and acting on its nodes (that is: the `%import` directive nodes). That's what the compiler does, neither the parser nor any parse tree node -> Kotlin AST node transformation step. This can be seen from how hard it is, and how boiler plate / bogus is needed for testing just this module, `compilerAst` alone.
* Actually, it did *not* make the missing file names disappear *completely*, as I've found out today. It's rather intricate, and I won't give it away yet, just to illustrate my points below regarding tests in general.

The other two quirks, errors not reported in order and "strstr" I'd put aside for now, too.

As for tests/testability in general:
* separate branch, for sure
* I'm a big believer in test-first, but that's just not how things are right now. So I think you can guess that I cannot agree with "unit tests are nice, but will be written later". This way, they never will be.
* But: I do NOT propose to sit down and write tests for everything that's already there. That won't work either.
* What I do propose is this: write tests *from now **on***, and keep refactoring.
* That's realistic, and I'm dead-sure that it'll pay off sooner than you think.

**Comment by meisl** [comment] 2021-06-19 20:43
Hi @irmen,

I started to work on testability, and ultimately fixing this issue properly, on the branch [`refactor_parsing` in my fork](https://github.com/meisl/prog8/tree/refactor_parsing).

It's only a first attempt, and might well be thrown away. I just need to fiddle around, in order to familiarize myself better with the code base. However, I don't think that my first steps are *completely* bogus, so maybe they're of interest for you - even at this very early stage.

A few thoughts/plans, which might not be so obvious from the few commits:
* The interface/API provided by ANTLR is pretty complex, only a very limited subset of it is in fact used / needed.
* So let's make that really explicit and concentrate it in one place. To make it simple - and testable. This is the new and very limited Kotlin class `Prog8Parser`. Anything else should go through this, and *only this*. (the generated java parser is now called `Prog8ANTLRParser`, not least to *discourage* using it). You get, however, (Kotlin) `prog8.ast` nodes from it, no `RuleContext`s.
* I plan to make it so you can register one (!) very simple listener with `Prog8Parser`, and it's purpose is really nothing else than to collect error messages. NOT: throw on its own, or otherwise influence the process of parsing. This listener will be something new, NOT a `org.antlr.v4.runtime.ANTLRErrorListener`. Pretty much the already existing `prog8.compiler.ErrorReporter`.
* I am trying to hide all the ANTLR stuff, including `ErrorStrategy` from anywhere outside `Prog8Parser`.
* There is currently (ie on master) a really unhealthy variety of errors/exceptions, and their proper use is unclear. E.g. ModuleImporter throws `ParsingFailedError` if the file it is asked to import does not exist. However, not finding a file is *definitely NOT a parsing problem*. Therefore I started by introducing `ParseError`, the only thing ever reported from `Prog8Parser`. Atm it's a subclass of `ParsingFailedError`, but only for the time being.
* As I already mentioned above, actually *importing modules* will eventually go into the compiler package, not the parser/AST one (currently named `compilerAst`)
* Once I've made more progress with the refactorings, and actually **got things working again**, I'll think about renaming. Until then I'll stick with the old names. Otherwise we'd most probably have a hard time naming things in discussions.

**Again, keep in mind that this is really very early-stage - quite some things are broke!**
I'll invite you as collaborator to my fork anyways.

**Comment by meisl** [comment] 2021-06-19 20:58
Damn, I actually forgot the main thing, which is how I actually imagine to approach *this issue*:
* the **location of errors** is to be handled by *one thing only*, namely `Position`
* any `ParseError` will have a proper `Position` on it (no more "<unknown>" - more informative)
* in case of success the AST nodes returned from `Prog8Paser` will have positions on them, so if the compiler finds any problems it can issue its own errors based on these

**Comment by irmen** [comment] 2021-06-23 17:14
just a heads up I may not be able to spend as much time on prog8 as I was the past few weeks

**Comment by meisl** [comment] 2021-06-23 17:24
Thanks & ok. I'll just keep on plowing my way on the branch in the fork. I'll also try to condense my reasoning/conclusions in a README, say "CompilerDevelopment.md".
Btw: for me it's mostly the weekend, and a bit of Friday.

**Comment by irmen** [comment] 2021-07-02 18:46
Once the CompilerDevelopment.md contains the results of the analysis above, can this issue be closed you think?

**Comment by meisl** [comment] 2021-07-03 11:18
The .md is *based* on the above, the issue will be resolved once the plan is *executed*.

The current state in my fork is right before moving `ModuleImporter` to `compiler`. I can't actually tell off hand if the problem is still in there, I'd say it would also need at least a little bit of do-over - and more tests - to deem this issue resolved.

**Comment by meisl** [comment] 2021-07-03 11:24
Sorry, I should have been more clear: contrary to what it says in the OP, the problem showed up also elsewhere in ModuleImporter, under rather intricate circumstances; which kind of source module imports which and where the error occurs.

**Comment by meisl** [comment] 2021-07-03 11:32
[cross-ref to #50]

**Comment by irmen** [comment] 2021-07-03 11:53
Okay I didn't realize the issue still was present. Let's keep this open then.

**Comment by irmen** [comment] 2021-10-13 21:54
I wonder where this bug occurs now still... haven't seen it yet myself

**Comment by irmen** [comment] 2021-10-18 22:23
``SourceCode`` now sets the underlying antlr CharStream's file component, for filesystem sources, embedded resources, _and_ string sources. The only source it can't be set is for generated Node objects.

**Comment by irmen** [comment] 2021-10-30 15:06
Also now got rid of the confusing ParsingFailedError. (in 7.2)

As I'm not able to reproduce a problem anymore with reporting failed source paths, I'm now closing this issue.

**Closed by irmen** 2021-10-30 15:06 UTC
Labels: bug
