### ISSUE TITLE
Unexpected behavior of `and` operator [is actually X register corruption]

### ISSUE THREAD

**Issue by megagrump** [irmen/prog8#94] opened 2023-01-23 11:23 UTC
Running this code (modified `examples/cx16/keyboardhandler.p8` and pressing F1 should print
`F1 WAS PRESSED`
`CONFIRMED.`

But it does not print the `CONFIRMED.` line, which defies all logic: `prefix == 0` is `true`, `scancode == 5` is `true`, but `(prefix == 0) and (scancode == 5)` is supposedly `false`?

This does only happen when the function is called by the shim. Output is correct when calling the function manually.
```
%option no_sysinit
%import textio

main {
	sub start() {
		sys.set_irqd()
		cx16.KEYHDL = &main.keyboard_scancode_handler.asm_shim
		sys.clear_irqd()
		repeat {
		}
	}

	sub keyboard_scancode_handler(ubyte prefix, ubyte scancode, bool updown) -> bool {
		if updown return true

		if prefix == 0 {
			if scancode == 5 {
				txt.print("f1 was pressed\n")
				if (prefix == 0) and (scancode == 5) {
					txt.print("confirmed.\n")
				}
			}
		}

		return true

asm_shim:
		%asm {{
			php
			pha
			phx
			stz  updown
			bcc  +
			inc  updown
+			stx  prefix
			sta  scancode
			jsr  keyboard_scancode_handler
			beq  +
			plx
			pla
			lda #0     ;By setting A=0 we will consume this key event
			tax
			plp
			rts
+			plx
			pla     ; leave A untouched, continue processing
			plp
			rts
		}}
	}
}
```

**Comment by megagrump** [comment] 2023-01-23 14:02
I could reproduce the broken behavior with `prog8compiler-8.8.1-all.jar` and latest git master, which compiled to `prog8compiler-8.9-dev-all.jar`.

**Comment by irmen** [comment] 2023-01-23 23:02
Thanks for reporting, this is a nasty one.

The problem is that the X register gets clobbered in the `asm_shim` routine when that gets called by the kernal's interrupt handler that detected a key event. Prog8 code needs the X register to correctly point to its internal evaluation stack location that it needs to correctly evaluate certain expressions.

In this case, the `(prefix == 0) and (scancode == 5)` is such an expression and because the X register got messed up, it no longer evaluates to the correct result. You can verify this by replacing it by the following piece of code that gets translated in assembly without using that evaluation stack, and suddenly the code starts working: 
```
bool both = prefix==0
both &= scancode==5
if both {
    txt.print("confirmed.\n")
}
```

Alternatively you can temporarily add a `ldx #10` immediately before the `jsr  keyboard_scancode_handler` in the `asm_shim` routine and it starts working again as well.

Both are not permanent solutions though.  I'm not yet sure how to proceed with this.

**Comment by irmen** [comment] 2023-01-24 00:31
I've updated the keyboardhandler example to work around the X register issue.

**Comment by megagrump** [comment] 2023-01-29 14:26
What does this mean for other KERNAL vectors, or IRQ handlers? This sounds like you can't safely make use of those in any prog8 program.

**Comment by irmen** [comment] 2023-01-30 16:47
Good question.
However, the kernal doesn't change the X register before calling into the irq handler. So we can assume it is still pointing to a valid location in the evaluation stack page.

**Comment by megagrump** [comment] 2023-01-30 17:45
> the kernal doesn't change the X register before calling into the irq handler

I do not understand how the X register can *not* be random anytime an IRQ occurs. We've just interrupted some code that probably used the X register... how does this work? I must be missing something, lol.

**Comment by irmen** [comment] 2023-01-30 21:01
It is assumed that the code interrupted is prog8 code, so the X register is pointing to the top (or bottom if you wish) of the eval stack. As such it can be safely used in the interrupt handler, as the eval stack simply grows and shrinks further. 

Now that I write this, I do realize that this is not guaranteed...: also routines not written in prog8,  such as kernal routines, that clobber the X register, could be interrupted.... and *then* the X register will be invalid... :-(

I am unsure what to do with this insight right now....

**Comment by megagrump** [comment] 2023-01-30 21:27
Can you make the one byte in the ZP a requirement for prog8 programs, and make the exact location an `%option`?

**Comment by irmen** [comment] 2023-01-30 22:16
Can you elaborate? What byte do you mean?

**Comment by megagrump** [comment] 2023-01-30 22:22
I mean the byte of memory that you require to store the stack pointer. If you can't reliably store it in X, can you store it in ZP instead and retrieve it from there?

**Comment by irmen** [comment] 2023-01-30 23:14
That would make all evaluation stack operations extremely slow as it needs to store and retrieve the byte from memory on every operation....

**Closed** 2023-03-10 22:29 UTC
